language: rust
sudo: false

rust:
    - nightly

os:
    - linux

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libssl-dev

before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

script:
- |
    travis-cargo build && travis-cargo test &&
    travis-cargo build --features tls && travis-cargo test --features tls

after_success:
- travis-cargo coveralls --no-sudo

env:
  global:
    # override the default `--features unstable` used for the nightly branch
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
