// Copyright 2018 Google LLC
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT.

#![feature(async_await)]

use gumdrop::Options;
use std::io;
use tarpc::{client, context};
use std::net::SocketAddr;

#[derive(Options)]
struct ClientOptions {
    help: bool,
    #[options(
        help = "the server address to connect to",
        required,
        default_expr = "([0, 0, 0, 0], 0).into()",
        parse(try_from_str))]
    server_addr: SocketAddr,
    #[options(command, required)]
    method: Option<Method>,
}

#[derive(Options)]
enum Method {
    #[options(help = "say hello")]
    Hello(HelloOpts),
    #[options(help = "shut down the server")]
    ShutDown(ShutDownOpts),
}

#[derive(Options)]
struct HelloOpts {
    #[options(help = "the name to say hello to", required)]
    name: String,
}

#[derive(Options)]
struct ShutDownOpts {}

#[runtime::main(runtime_tokio::Tokio)]
async fn main() -> io::Result<()> {
    let opts = ClientOptions::parse_args_default_or_exit();

    let transport = json_transport::connect(&opts.server_addr).await?;

    // WorldClient is generated by the service attribute. It has a constructor `new` that takes a
    // config and any Transport as input.
    let mut client = service::WorldClient::new(client::Config::default(), transport).spawn()?;

    // The client has an RPC method for each RPC defined in the annotated trait. It takes the same
    // args as defined, with the addition of a Context, which is always the first arg. The Context
    // specifies a deadline and trace information which can be helpful in debugging requests.
    match opts.method.unwrap() {
        Method::Hello(opts) => {
            let hello = client.hello(context::current(), opts.name).await?;
            println!("{}", hello);
        }
        Method::ShutDown(_) => {
            client.shut_down(context::current()).await?;
            println!("Shutdown commenced.");
        }
    }

    Ok(())
}
