// Copyright 2018 Google LLC
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT.

#![feature(async_await)]

use futures::{
    future::{self, Ready},
    prelude::*,
};
use gumdrop::Options;
use service::World;
use std::{io, net::SocketAddr};
use tarpc::{
    context,
    server::{self, Channel, Handler},
};
use futures::future::{AbortHandle, Abortable, Aborted};

// This is the type that implements the generated World trait. It is the business logic
// and is used to start the server.
#[derive(Clone)]
struct HelloServer {
    client_addr: SocketAddr,
    abort_handle: AbortHandle,
}

impl World for HelloServer {
    // Each defined rpc generates two items in the trait, a fn that serves the RPC, and
    // an associated type representing the future output by the fn.

    type HelloFut = Ready<String>;

    fn hello(self, _: context::Context, name: String) -> Self::HelloFut {
        future::ready(format!(
            "Hello, {}! You are connected from {:?}.",
            name, self.client_addr
        ))
    }

    type ShutDownFut = Ready<()>;
    fn shut_down(self, _: context::Context) -> Self::ShutDownFut {
        self.abort_handle.abort();
        future::ready(())
    }
}

#[derive(Options)]
struct ServerOptions {
    help: bool,
    #[options(help = "the port number to listen on", required)]
    port: u16,
}

#[runtime::main(runtime_tokio::Tokio)]
async fn main() -> io::Result<()> {
    env_logger::init();

    let opts = ServerOptions::parse_args_default_or_exit();
    let server_addr = ([0, 0, 0, 0], opts.port).into();

    // json_transport is provided by the associated crate tarpc-json-transport. It makes it easy
    // to start up a serde-powered json serialization protocol over TCP.
    let (abort_handle, registration) = futures::future::AbortHandle::new_pair();
    let server = json_transport::listen(&server_addr)?
        // Ignore accept errors.
        .filter_map(|r| future::ready(r.ok()))
        .map(server::BaseChannel::with_defaults)
        // Limit channels to 1 per IP.
        .max_channels_per_key(1, |t| t.as_ref().peer_addr().unwrap().ip())
        // serve is generated by the service attribute. It takes as input any type implementing
        // the generated World trait.
        .map(move |channel| {
            let server = HelloServer {
                client_addr: channel.as_ref().as_ref().peer_addr().unwrap(),
                abort_handle: abort_handle.clone(),
            };
            runtime::spawn(channel.respond_with(server.serve()).execute())
        })
        // Max 10 channels.
        .buffer_unordered(10)
        .for_each(|_| async {});
    if let Err(Aborted) = Abortable::new(server, registration).await {
        eprintln!("Server in lame duck mode.");
    }

    Ok(())
}
