[package]
name = "example-service"
version = "0.1.0"
authors = ["Tim Kuehn <tikue@google.com>"]
edition = "2018"

[dependencies]
bincode-transport = { path = "../bincode-transport" }
futures-preview = { version = "0.3.0-alpha.6", features = ["compat", "tokio-compat"] }
serde = { version = "1.0" }
tarpc = { path = "../tarpc", features = ["serde"] }
tarpc-plugins = { path = "../plugins" }
tokio = "0.1"

[lib]
name = "service"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/main.rs"
